apiVersion: v2
name: kubarr-backend
description: Kubarr API backend
type: application
version: 0.2.3
annotations:
  kubarr.io/display-name: "Kubarr Backend"
  kubarr.io/icon: "🧠"
  kubarr.io/category: "system"
  kubarr.io/system: "true"
  kubarr.io/hidden: "false"
  kubarr.io/browseable: "false"
dependencies:
  - name: kubarr-common
    version: 0.3.2
    repository: file://../kubarr-common
