apiVersion: v2
name: frigate
description: Frigate local NVR and camera object detection
type: application
version: 0.18.0+3
appVersion: "0.18.0"
annotations:
  kubarr.io/display-name: "Frigate"
  kubarr.io/icon: "📹"
  kubarr.io/category: "media-server"
dependencies:
  - name: kubarr-common
    version: 0.3.4
    repository: file://../../system/kubarr-common
