apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redmine.fullname" . }}-rack
  namespace: {{ .Values.namespace.name }}
data:
  config.ru: |
    require_relative 'config/environment'
    map '/redmine' do
      run Rails.application
    end
