apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frigate.fullname" . }}-seed
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- .Values.config | nindent 4 }}
