{{- $listenPort := ternary (randInt 49152 65535) 6881 .Values.vpn.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qbittorrent.fullname" . }}-qbittorrent-conf
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
data:
  qBittorrent.conf: |
    [AutoRun]
    enabled=false
    program=

    [BitTorrent]
    Session\AddTorrentStopped=false
    Session\DefaultSavePath=/downloads/
    Session\Port={{ $listenPort }}
    Session\QueueingSystemEnabled=true
    Session\ShareLimitAction=Stop
    Session\TempPath=/downloads/incomplete/
    {{- with .Values.qbittorrent.qbittorrentConf.BitTorrent }}
    {{- range $key, $value := . }}
    {{ $key }}={{ $value }}
    {{- end }}
    {{- end }}

    [LegalNotice]
    Accepted=true

    [Network]
    PortForwardingEnabled={{ ternary "true" "false" .Values.vpn.enabled }}
    Proxy\HostnameLookupEnabled=false
    Proxy\Profiles\BitTorrent=true
    Proxy\Profiles\Misc=true
    Proxy\Profiles\RSS=true

    [Preferences]
    Connection\PortRangeMin={{ $listenPort }}
    Connection\UPnP={{ ternary "true" "false" .Values.vpn.enabled }}
    Downloads\SavePath=/downloads/
    Downloads\TempPath=/downloads/incomplete/
    WebUI\Address=0.0.0.0
    WebUI\ServerDomains=*
    WebUI\LocalHostAuth=false
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\AuthSubnetWhitelist=10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
    WebUI\CSRFProtection=false
    WebUI\ClickjackingProtection=false
    WebUI\HostHeaderValidation=false
