apiVersion: v2
name: postgresql
description: Plain PostgreSQL database for kubarr
type: application
version: 16.1.3
annotations:
  kubarr.io/display-name: "PostgreSQL"
  kubarr.io/icon: "🐘"
  kubarr.io/category: "system"
  kubarr.io/system: "true"
dependencies:
  - name: kubarr-common
    version: 0.3.2
    repository: file://../kubarr-common
