apiVersion: v2
name: kubarr-worker
description: Kubarr lifecycle worker
type: application
version: 0.2.4
annotations:
  kubarr.io/display-name: "Kubarr Worker"
  kubarr.io/icon: "⚙️"
  kubarr.io/category: "system"
  kubarr.io/system: "true"
  kubarr.io/hidden: "false"
  kubarr.io/browseable: "false"
dependencies:
  - name: kubarr-common
    version: 0.3.2
    repository: file://../kubarr-common
